### ISSUE TITLE
Request for some improvements

### ISSUE THREAD

**Issue by NotteShock** [GreenCityLife/Green-Coder#2]
The icons in the bottomsheet looks too big, like that
![Screenshot_2022-01-19-12-57-56-512_com greencitylife greencoder](https://user-images.githubusercontent.com/85934291/150072813-06c8aafc-11f3-427c-a2f5-97568259646f.jpg)
Also why the create project button in this dialog is in the left? 
![IMG_20220119_130038](https://user-images.githubusercontent.com/85934291/150073271-8bdaec32-7bdf-4c4d-9098-b91e95161556.jpg)
Because most of right handed people will click on the right button by default but that button is the "nevermind" button, swap the button position seems better IMO

**Comment by GreenCityLife** [comment]
:hidepain: I will solve it thanks

**Comment by GreenCityLife** [comment]
Is this size ok for you?
![Screenshot_20220122-170924](https://user-images.githubusercontent.com/86912846/150637045-8af34562-9da1-4a26-a969-678cf69609a3.jpg)

**Comment by NotteShock** [comment]
> Is this size ok for you? ![Screenshot_20220122-170924](https://user-images.githubusercontent.com/86912846/150637045-8af34562-9da1-4a26-a969-678cf69609a3.jpg)

well, it looks really good
